#!/bin/bash
# /etc/init.d/ybnn

### BEGIN INIT INFO
# Provides: embbnux
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: ledblink initscript
# Description: This service is used to manage a led
### END INIT INFO

case "$1" in
    start)
        echo "Starting YBNN"
        python3 /home/pi/ybnn/mainAPP.py &
        ;;
    stop)
        echo "Stopping YBNN"
        #killall mainAPP.py
        pkill python3
        ;;
    *)
        echo "Usage: service ybnn start|stop|status"
        exit 1
        ;;
esac
exit 0